// Generated by tools/build-mobile-contracts.mjs from packages/contracts/schemas. Do not edit.
//
// The Agent bundle runs in an Android WebView, which has no filesystem, so the contract schemas the
// phone runtime validates against are baked in here rather than read from disk. The Node validator
// keeps reading the same files directly; tests/scenarios/mobile-agent-contracts.test.ts compares
// this module against them so the two bindings cannot drift.
import type { JsonSchema } from "./contract-schemas.ts";

export const CONTRACT_SCHEMAS: Readonly<Record<string, JsonSchema>> = {
  "destination-candidates.schema.json": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://leqi-ai-glasses.dev/contracts/destination-candidates.schema.json",
    "title": "Destination candidates",
    "type": "object",
    "required": [
      "schema_version",
      "query_id",
      "session_id",
      "generated_at",
      "candidates"
    ],
    "properties": {
      "schema_version": {
        "type": "string",
        "pattern": "^[0-9]+\\.[0-9]+$"
      },
      "query_id": {
        "type": "string",
        "minLength": 1
      },
      "session_id": {
        "type": "string",
        "minLength": 1
      },
      "generated_at": {
        "type": "string",
        "format": "date-time"
      },
      "candidates": {
        "type": "array",
        "maxItems": 5,
        "items": {
          "type": "object",
          "required": [
            "candidate_id",
            "name",
            "provider"
          ],
          "properties": {
            "candidate_id": {
              "type": "string",
              "minLength": 1
            },
            "name": {
              "type": "string",
              "minLength": 1
            },
            "address": {
              "type": "string"
            },
            "category": {
              "type": "string"
            },
            "distance_m": {
              "type": "number",
              "minimum": 0
            },
            "location": {
              "type": "object",
              "required": [
                "lng",
                "lat"
              ],
              "properties": {
                "lng": {
                  "type": "number",
                  "minimum": -180,
                  "maximum": 180
                },
                "lat": {
                  "type": "number",
                  "minimum": -90,
                  "maximum": 90
                }
              },
              "additionalProperties": false
            },
            "provider": {
              "type": "string",
              "minLength": 1
            }
          },
          "additionalProperties": false
        }
      }
    },
    "additionalProperties": false
  },
  "destination-confirmation-tool-input.schema.json": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://leqi-ai-glasses.dev/contracts/destination-confirmation-tool-input.schema.json",
    "title": "Destination confirmation tool input",
    "type": "object",
    "required": [
      "candidate_id"
    ],
    "properties": {
      "candidate_id": {
        "type": "string",
        "minLength": 1
      }
    },
    "additionalProperties": false
  },
  "destination-query.schema.json": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://leqi-ai-glasses.dev/contracts/destination-query.schema.json",
    "title": "Destination query",
    "type": "object",
    "required": [
      "schema_version",
      "query_id",
      "session_id",
      "transcript",
      "locale",
      "requested_at"
    ],
    "properties": {
      "schema_version": {
        "type": "string",
        "pattern": "^[0-9]+\\.[0-9]+$"
      },
      "query_id": {
        "type": "string",
        "minLength": 1
      },
      "session_id": {
        "type": "string",
        "minLength": 1
      },
      "transcript": {
        "type": "string",
        "minLength": 1
      },
      "locale": {
        "type": "string",
        "minLength": 2
      },
      "requested_at": {
        "type": "string",
        "format": "date-time"
      }
    },
    "additionalProperties": false
  },
  "fact.schema.json": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://leqi-ai-glasses.dev/contracts/fact.schema.json",
    "title": "Observation fact",
    "description": "可被领域策略消费的命名事实。新增能力通过新增 fact name，而不是修改核心结果结构。",
    "type": "object",
    "required": [
      "name",
      "value",
      "confidence"
    ],
    "properties": {
      "name": {
        "type": "string",
        "pattern": "^[a-z][a-z0-9_-]*(\\.[a-z0-9_-]+)+$"
      },
      "value": {},
      "confidence": {
        "enum": [
          "high",
          "medium",
          "low",
          "unknown"
        ]
      },
      "valid_until": {
        "type": "string",
        "format": "date-time"
      },
      "source": {
        "type": "string"
      },
      "evidence": {
        "type": "array",
        "items": {
          "type": "string"
        }
      }
    },
    "additionalProperties": false
  },
  "facts-query-tool-input.schema.json": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://leqi-ai-glasses.dev/contracts/facts-query-tool-input.schema.json",
    "title": "Facts query tool input",
    "type": "object",
    "required": [
      "names"
    ],
    "properties": {
      "names": {
        "type": "array",
        "minItems": 1,
        "items": {
          "type": "string"
        }
      },
      "scope": {
        "enum": [
          "current_session",
          "recent_observation",
          "navigation_context"
        ]
      },
      "limit": {
        "type": "integer",
        "minimum": 1,
        "maximum": 20
      }
    },
    "additionalProperties": false
  },
  "navigation-start-tool-input.schema.json": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://leqi-ai-glasses.dev/contracts/navigation-start-tool-input.schema.json",
    "title": "Navigation start tool input",
    "type": "object",
    "required": [
      "candidate_id"
    ],
    "properties": {
      "candidate_id": {
        "type": "string",
        "minLength": 1
      },
      "mode": {
        "enum": [
          "walking",
          "transit",
          "unknown"
        ]
      }
    },
    "additionalProperties": false
  },
  "observation-tool-input.schema.json": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://leqi-ai-glasses.dev/contracts/observation-tool-input.schema.json",
    "title": "Observation tool input",
    "type": "object",
    "required": [
      "capability_id",
      "capture_mode",
      "consent"
    ],
    "properties": {
      "capability_id": {
        "type": "string",
        "pattern": "^[a-z][a-z0-9]*(\\.[a-z0-9_-]+)+$"
      },
      "capture_mode": {
        "enum": [
          "single_frame",
          "short_window"
        ]
      },
      "consent": {
        "enum": [
          "explicit",
          "preauthorized"
        ]
      },
      "context": {
        "type": "object"
      },
      "request_reason": {
        "type": "string"
      },
      "max_age_ms": {
        "type": "integer",
        "minimum": 0
      }
    },
    "additionalProperties": false
  },
  "session-cancel-tool-input.schema.json": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://leqi-ai-glasses.dev/contracts/session-cancel-tool-input.schema.json",
    "title": "Session cancel tool input",
    "type": "object",
    "required": [
      "reason"
    ],
    "properties": {
      "reason": {
        "type": "string",
        "minLength": 1
      },
      "user_initiated": {
        "type": "boolean"
      }
    },
    "additionalProperties": false
  },
  "speech-ask-user.schema.json": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://leqi-ai-glasses.dev/contracts/speech-ask-user.schema.json",
    "title": "Speech ask user input",
    "type": "object",
    "required": [
      "prompt_template",
      "expected_intents",
      "expires_at"
    ],
    "properties": {
      "prompt_template": {
        "type": "string",
        "minLength": 1
      },
      "parameters": {
        "type": "object"
      },
      "expected_intents": {
        "type": "array",
        "minItems": 1,
        "items": {
          "type": "string"
        }
      },
      "expires_at": {
        "type": "string",
        "format": "date-time"
      }
    },
    "additionalProperties": false
  }
} as const;
